'use client';

import { useState } from 'react';
import type { ImageAsset } from '@/lib/media/provider';
import type { RecognitionExercise, RecognitionResult } from '@/lib/exercises/image-id';
import { Button } from './ui';

// Recognition-phase image identification (GT-202). The image arrives as an
// adapter-served asset; grading happens in the caller (which owns corpus
// data and the grammar-log write path) and the result renders warmly here.

export function ImageIdExercise({
  exercise,
  image,
  onChoose,
  result,
}: {
  exercise: RecognitionExercise;
  image: ImageAsset;
  onChoose: (wordId: string) => void;
  result: RecognitionResult | null;
}) {
  const [chosen, setChosen] = useState<string | null>(null);

  return (
    <div className="flex flex-col gap-4" data-testid="image-id-exercise">
      {image.source.type === 'inline-svg' ? (
        <div
          className="max-w-xs"
          data-testid="image-id-image"
          role="img"
          aria-label="Picture of a vocabulary word to identify"
          // Placeholder SVGs are generated by our own provider from validated
          // vocabulary data; no untrusted markup enters this path.
          dangerouslySetInnerHTML={{ __html: image.source.svg }}
        />
      ) : (
        /* eslint-disable-next-line @next/next/no-img-element */
        <img
          src={image.source.url}
          alt="Picture of a vocabulary word to identify"
          className="max-w-xs"
          data-testid="image-id-image"
        />
      )}

      <div className="flex flex-col items-start gap-2">
        {exercise.options.map((option) => (
          <Button
            key={option.wordId}
            variant="secondary"
            className={chosen === option.wordId ? 'ring-2 ring-[var(--color-focus-ring)]' : ''}
            disabled={result !== null}
            aria-pressed={chosen === option.wordId}
            onClick={() => {
              setChosen(option.wordId);
              onChoose(option.wordId);
            }}
            data-testid={`image-id-option-${option.wordId}`}
          >
            {option.label}
          </Button>
        ))}
      </div>

      {result ? (
        <p data-testid="image-id-feedback" role="status">
          {result.correct
            ? 'Genau! You got it, article and all.'
            : `Not quite. It is ${result.correctLabel}. On we go!`}
        </p>
      ) : null}
    </div>
  );
}
