import { grammarItemSchema, unitSchema, type GrammarItem, type Unit } from '@/lib/db/curriculum';

// Versioned curriculum skeleton (GT-101). Grammar progression follows PRD 3.1
// and Section 6: Akkusativ late A1, Dativ mid A2, Genitiv plus adjective
// endings plus verb-final clauses at B1. Weights: 3x genders/articles, cases,
// adjective endings; 2x word order, separable verbs, pronunciation; 1x rest.

export const SEED_VERSION = 1;

const grammarItems: GrammarItem[] = [
  // A1
  { id: 'pronunciation-ch-umlauts', name: 'Pronunciation: ch, ü/ö/ä, ß', level: 'A1', weight: 2 },
  { id: 'v2-statements', name: 'Verb-second word order in statements', level: 'A1', weight: 2 },
  {
    id: 'personal-pronouns',
    name: 'Personal pronouns (ich, du, er/sie/es)',
    level: 'A1',
    weight: 1,
  },
  { id: 'sein-haben-present', name: 'sein and haben in the present tense', level: 'A1', weight: 1 },
  {
    id: 'teen-numbers-pattern',
    name: 'Numbers: the root+zehn pattern and its exceptions',
    level: 'A1',
    weight: 1,
  },
  { id: 'weekdays-time', name: 'Weekdays (-tag pattern) and telling time', level: 'A1', weight: 1 },
  {
    id: 'noun-genders-articles',
    name: 'Noun genders and articles (der/die/das)',
    level: 'A1',
    weight: 3,
  },
  { id: 'plural-die', name: 'Plurals always take die', level: 'A1', weight: 1 },
  {
    id: 'v2-inversion-questions',
    name: 'Questions by subject-verb inversion',
    level: 'A1',
    weight: 2,
  },
  {
    id: 'present-tense-regular',
    name: 'Regular present-tense conjugation',
    level: 'A1',
    weight: 1,
  },
  { id: 'akkusativ-intro', name: 'Akkusativ: introduction (den, einen)', level: 'A1', weight: 3 },
  {
    id: 'akkusativ-pronouns',
    name: 'Akkusativ pronouns (mich, dich, ihn)',
    level: 'A1',
    weight: 3,
  },
  // A2
  { id: 'separable-verbs', name: 'Separable verbs and the verb bracket', level: 'A2', weight: 2 },
  {
    id: 'present-irregular',
    name: 'Irregular present-tense verbs (stem changes)',
    level: 'A2',
    weight: 1,
  },
  { id: 'modal-verbs', name: 'Modal verbs (können, müssen, wollen)', level: 'A2', weight: 1 },
  {
    id: 'modal-bracket-order',
    name: 'Word order with modals (bracket to the end)',
    level: 'A2',
    weight: 2,
  },
  { id: 'dativ-intro', name: 'Dativ: introduction (dem, einer)', level: 'A2', weight: 3 },
  { id: 'dativ-pronouns', name: 'Dativ pronouns (mir, dir, ihm)', level: 'A2', weight: 3 },
  { id: 'perfekt-haben', name: 'Perfekt with haben', level: 'A2', weight: 1 },
  { id: 'perfekt-sein', name: 'Perfekt with sein (movement and change)', level: 'A2', weight: 1 },
  {
    id: 'comparatives-superlatives',
    name: 'Comparatives and superlatives',
    level: 'A2',
    weight: 1,
  },
  {
    id: 'two-way-prepositions',
    name: 'Two-way prepositions (Akkusativ vs Dativ)',
    level: 'A2',
    weight: 3,
  },
  {
    id: 'coordinating-conjunctions',
    name: 'Coordinating conjunctions (und, aber, denn)',
    level: 'A2',
    weight: 1,
  },
  // B1
  { id: 'verb-final-subordinate', name: 'Verb-final subordinate clauses', level: 'B1', weight: 2 },
  { id: 'dass-weil-clauses', name: 'dass and weil clauses', level: 'B1', weight: 2 },
  { id: 'genitiv', name: 'Genitiv case', level: 'B1', weight: 3 },
  { id: 'relative-clauses', name: 'Relative clauses', level: 'B1', weight: 2 },
  { id: 'adjective-endings', name: 'Adjective endings (decision rules)', level: 'B1', weight: 3 },
  {
    id: 'attributive-comparatives',
    name: 'Attributive comparatives (der bessere Weg)',
    level: 'B1',
    weight: 1,
  },
  { id: 'konjunktiv2', name: 'Konjunktiv II (würde, hätte, wäre)', level: 'B1', weight: 1 },
  { id: 'wenn-clauses', name: 'Conditional wenn-clauses', level: 'B1', weight: 2 },
  { id: 'passive-voice', name: 'Passive voice (present and past)', level: 'B1', weight: 1 },
  { id: 'man-constructions', name: 'man as a passive alternative', level: 'B1', weight: 1 },
  { id: 'zu-infinitive', name: 'zu + infinitive constructions', level: 'B1', weight: 1 },
  {
    id: 'opinion-discourse-markers',
    name: 'Opinion and argument discourse markers',
    level: 'B1',
    weight: 1,
  },
];

const units: Unit[] = [
  // A1: ~650 active words at exit
  {
    id: 'a1-1',
    level: 'A1',
    ordinal: 1,
    theme: 'Alphabet, sounds, and first greetings',
    grammarItemIds: ['pronunciation-ch-umlauts', 'v2-statements'],
    vocabSetRef: 'vocab-a1-1',
    capstoneDialogueRef: 'capstone-a1-1',
    capstonePremise: 'Greeting a neighbor in the stairwell and introducing yourself by name',
    targetWordCount: 100,
  },
  {
    id: 'a1-2',
    level: 'A1',
    ordinal: 2,
    theme: 'Introducing yourself and others',
    grammarItemIds: ['personal-pronouns', 'sein-haben-present'],
    vocabSetRef: 'vocab-a1-2',
    capstoneDialogueRef: 'capstone-a1-2',
    capstonePremise: 'Meeting a new colleague and exchanging names, origins, and jobs',
    targetWordCount: 105,
  },
  {
    id: 'a1-3',
    level: 'A1',
    ordinal: 3,
    theme: 'Numbers, days, and time',
    grammarItemIds: ['teen-numbers-pattern', 'weekdays-time'],
    vocabSetRef: 'vocab-a1-3',
    capstoneDialogueRef: 'capstone-a1-3',
    capstonePremise: 'Arranging to meet a friend at a specific day and time',
    targetWordCount: 110,
  },
  {
    id: 'a1-4',
    level: 'A1',
    ordinal: 4,
    theme: 'Home and everyday objects',
    grammarItemIds: ['noun-genders-articles', 'plural-die'],
    vocabSetRef: 'vocab-a1-4',
    capstoneDialogueRef: 'capstone-a1-4',
    capstonePremise: 'Showing a visitor around your apartment, naming rooms and objects',
    targetWordCount: 110,
  },
  {
    id: 'a1-5',
    level: 'A1',
    ordinal: 5,
    theme: 'Food, drink, and asking questions',
    grammarItemIds: ['v2-inversion-questions', 'present-tense-regular'],
    vocabSetRef: 'vocab-a1-5',
    capstoneDialogueRef: 'capstone-a1-5',
    capstonePremise: 'Ordering breakfast at a Berlin café and asking about the menu',
    targetWordCount: 110,
  },
  {
    id: 'a1-6',
    level: 'A1',
    ordinal: 6,
    theme: 'Shopping and the Akkusativ',
    grammarItemIds: ['akkusativ-intro', 'akkusativ-pronouns'],
    vocabSetRef: 'vocab-a1-6',
    capstoneDialogueRef: 'capstone-a1-6',
    capstonePremise: 'Buying groceries at the Supermarkt and asking for things you cannot find',
    targetWordCount: 115,
  },
  // A2: ~1,300 cumulative words at exit
  {
    id: 'a2-1',
    level: 'A2',
    ordinal: 1,
    theme: 'Daily routine and separable verbs',
    grammarItemIds: ['separable-verbs', 'present-irregular'],
    vocabSetRef: 'vocab-a2-1',
    capstoneDialogueRef: 'capstone-a2-1',
    capstonePremise: 'Describing your workday routine to a friend, from aufstehen to einschlafen',
    targetWordCount: 105,
  },
  {
    id: 'a2-2',
    level: 'A2',
    ordinal: 2,
    theme: 'Errands, appointments, and modal verbs',
    grammarItemIds: ['modal-verbs', 'modal-bracket-order'],
    vocabSetRef: 'vocab-a2-2',
    capstoneDialogueRef: 'capstone-a2-2',
    capstonePremise: 'Calling a doctor to make an appointment you must, can, or want to change',
    targetWordCount: 110,
  },
  {
    id: 'a2-3',
    level: 'A2',
    ordinal: 3,
    theme: 'Getting around the city and the Dativ',
    grammarItemIds: ['dativ-intro', 'dativ-pronouns'],
    vocabSetRef: 'vocab-a2-3',
    capstoneDialogueRef: 'capstone-a2-3',
    capstonePremise: 'Asking a stranger for directions on the U-Bahn and helping another in turn',
    targetWordCount: 110,
  },
  {
    id: 'a2-4',
    level: 'A2',
    ordinal: 4,
    theme: 'Talking about the past (Perfekt)',
    grammarItemIds: ['perfekt-haben', 'perfekt-sein'],
    vocabSetRef: 'vocab-a2-4',
    capstoneDialogueRef: 'capstone-a2-4',
    capstonePremise: 'Telling a colleague about your weekend: where you went and what you did',
    targetWordCount: 110,
  },
  {
    id: 'a2-5',
    level: 'A2',
    ordinal: 5,
    theme: 'Comparing things: shopping and preferences',
    grammarItemIds: ['comparatives-superlatives', 'two-way-prepositions'],
    vocabSetRef: 'vocab-a2-5',
    capstoneDialogueRef: 'capstone-a2-5',
    capstonePremise: 'Comparing two apartments with a friend and deciding which is better',
    targetWordCount: 105,
  },
  {
    id: 'a2-6',
    level: 'A2',
    ordinal: 6,
    theme: 'Everyday correspondence and transactions',
    grammarItemIds: ['coordinating-conjunctions', 'two-way-prepositions', 'modal-verbs'],
    vocabSetRef: 'vocab-a2-6',
    capstoneDialogueRef: 'capstone-a2-6',
    capstonePremise: 'Writing to your landlord about a broken heater and following up in person',
    targetWordCount: 110,
  },
  // B1: ~2,400 cumulative words at exit (Goethe Wortliste scope)
  {
    id: 'b1-1',
    level: 'B1',
    ordinal: 1,
    theme: 'Opinions and subordinate clauses',
    grammarItemIds: ['verb-final-subordinate', 'dass-weil-clauses'],
    vocabSetRef: 'vocab-b1-1',
    capstoneDialogueRef: 'capstone-b1-1',
    capstonePremise: 'Discussing with a friend why you like (or avoid) social media',
    targetWordCount: 180,
  },
  {
    id: 'b1-2',
    level: 'B1',
    ordinal: 2,
    theme: 'Work and society, the Genitiv',
    grammarItemIds: ['genitiv', 'relative-clauses'],
    vocabSetRef: 'vocab-b1-2',
    capstoneDialogueRef: 'capstone-b1-2',
    capstonePremise: 'Workplace small talk about a colleague who changed careers',
    targetWordCount: 185,
  },
  {
    id: 'b1-3',
    level: 'B1',
    ordinal: 3,
    theme: 'Describing precisely: adjective endings',
    grammarItemIds: ['adjective-endings', 'attributive-comparatives'],
    vocabSetRef: 'vocab-b1-3',
    capstoneDialogueRef: 'capstone-b1-3',
    capstonePremise: 'Reporting a lost bag to the Fundbüro with exact descriptions',
    targetWordCount: 185,
  },
  {
    id: 'b1-4',
    level: 'B1',
    ordinal: 4,
    theme: 'Hypotheticals and polite requests (Konjunktiv II)',
    grammarItemIds: ['konjunktiv2', 'wenn-clauses'],
    vocabSetRef: 'vocab-b1-4',
    capstoneDialogueRef: 'capstone-b1-4',
    capstonePremise: 'An apartment viewing: polite questions and what you would change',
    targetWordCount: 185,
  },
  {
    id: 'b1-5',
    level: 'B1',
    ordinal: 5,
    theme: 'Media, news, and the passive voice',
    grammarItemIds: ['passive-voice', 'man-constructions'],
    vocabSetRef: 'vocab-b1-5',
    capstoneDialogueRef: 'capstone-b1-5',
    capstonePremise: 'Discussing a news story: what was reported and what is being done',
    targetWordCount: 180,
  },
  {
    id: 'b1-6',
    level: 'B1',
    ordinal: 6,
    theme: 'Argument and exam readiness',
    grammarItemIds: ['zu-infinitive', 'opinion-discourse-markers'],
    vocabSetRef: 'vocab-b1-6',
    capstoneDialogueRef: 'capstone-b1-6',
    capstonePremise: 'A structured debate: planning something together and defending a choice',
    targetWordCount: 185,
  },
];

export const seedGrammarItems: readonly GrammarItem[] = grammarItems.map((item) =>
  grammarItemSchema.parse(item),
);

export const seedUnits: readonly Unit[] = units.map((unit) => unitSchema.parse(unit));
